### ISSUE TITLE
Why is this useful?

### ISSUE THREAD

**Issue by petar-dambovaliev** [ashanbrown/makezero#16]
Using `append` on a non zero initialized slice is not a wrong thing to do.
You create a slice with 5 elements, you initialize them and then you want to append something to that.
This is not a special case. This is a completely plausable thing.
You would need to spam with `//nolint:makezero` in such cases.

**Comment by alingse** [comment]
@petar-dambovaliev don't panic,  we have already discussed some case here https://github.com/ashanbrown/makezero/pull/15 and hope you provide your opinion

**Comment by ashanbrown** [comment]
@petar-dambovaliev As @alingse shows at https://github.com/ashanbrown/makezero/pull/15#issuecomment-2067990088, this linter identifies a significant number real bugs.  The problem tends to be that that code authors know the capacity a priori but forget to set the length to 0 (see https://github.com/ashanbrown/makezero?tab=readme-ov-file#purpose).  It is not trivial to identify the intent of the author (as seen in the discussion over at https://github.com/ashanbrown/makezero/pull/15).
